# Generated by Django 6.1.1 on 2026-09-08 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(help_text='Unique student registration/roll number (e.g. STU-2026-0042)', max_length=30, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science & Engineering'), ('Information Tech', 'Information Technology'), ('Data Science', 'Data Science & AI'), ('Electrical Eng', 'Electrical & Electronics'), ('Mechanical Eng', 'Mechanical Engineering'), ('Business Admin', 'Business Administration')], default='Computer Science', max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['roll_number'],
            },
        ),
    ]
